// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.mackenziehigh.sexpr;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface message_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sexpr.message_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    java.util.List<com.mackenziehigh.sexpr.Message.node_t> 
        getNodesList();
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    com.mackenziehigh.sexpr.Message.node_t getNodes(int index);
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    java.util.List<? extends com.mackenziehigh.sexpr.Message.node_tOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    com.mackenziehigh.sexpr.Message.node_tOrBuilder getNodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code sexpr.message_t}
   */
  public  static final class message_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sexpr.message_t)
      message_tOrBuilder {
    // Use message_t.newBuilder() to construct.
    private message_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private message_t() {
      nodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private message_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodes_ = new java.util.ArrayList<com.mackenziehigh.sexpr.Message.node_t>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodes_.add(
                  input.readMessage(com.mackenziehigh.sexpr.Message.node_t.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mackenziehigh.sexpr.Message.internal_static_sexpr_message_t_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mackenziehigh.sexpr.Message.internal_static_sexpr_message_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mackenziehigh.sexpr.Message.message_t.class, com.mackenziehigh.sexpr.Message.message_t.Builder.class);
    }

    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<com.mackenziehigh.sexpr.Message.node_t> nodes_;
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    public java.util.List<com.mackenziehigh.sexpr.Message.node_t> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    public java.util.List<? extends com.mackenziehigh.sexpr.Message.node_tOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    public com.mackenziehigh.sexpr.Message.node_t getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .sexpr.node_t nodes = 1;</code>
     */
    public com.mackenziehigh.sexpr.Message.node_tOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mackenziehigh.sexpr.Message.message_t)) {
        return super.equals(obj);
      }
      com.mackenziehigh.sexpr.Message.message_t other = (com.mackenziehigh.sexpr.Message.message_t) obj;

      boolean result = true;
      result = result && getNodesList()
          .equals(other.getNodesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.message_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mackenziehigh.sexpr.Message.message_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sexpr.message_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sexpr.message_t)
        com.mackenziehigh.sexpr.Message.message_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_message_t_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_message_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mackenziehigh.sexpr.Message.message_t.class, com.mackenziehigh.sexpr.Message.message_t.Builder.class);
      }

      // Construct using com.mackenziehigh.sexpr.Message.message_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_message_t_descriptor;
      }

      public com.mackenziehigh.sexpr.Message.message_t getDefaultInstanceForType() {
        return com.mackenziehigh.sexpr.Message.message_t.getDefaultInstance();
      }

      public com.mackenziehigh.sexpr.Message.message_t build() {
        com.mackenziehigh.sexpr.Message.message_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mackenziehigh.sexpr.Message.message_t buildPartial() {
        com.mackenziehigh.sexpr.Message.message_t result = new com.mackenziehigh.sexpr.Message.message_t(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mackenziehigh.sexpr.Message.message_t) {
          return mergeFrom((com.mackenziehigh.sexpr.Message.message_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mackenziehigh.sexpr.Message.message_t other) {
        if (other == com.mackenziehigh.sexpr.Message.message_t.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mackenziehigh.sexpr.Message.message_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mackenziehigh.sexpr.Message.message_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mackenziehigh.sexpr.Message.node_t> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = new java.util.ArrayList<com.mackenziehigh.sexpr.Message.node_t>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mackenziehigh.sexpr.Message.node_t, com.mackenziehigh.sexpr.Message.node_t.Builder, com.mackenziehigh.sexpr.Message.node_tOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public java.util.List<com.mackenziehigh.sexpr.Message.node_t> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.node_t getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder setNodes(
          int index, com.mackenziehigh.sexpr.Message.node_t value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder setNodes(
          int index, com.mackenziehigh.sexpr.Message.node_t.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder addNodes(com.mackenziehigh.sexpr.Message.node_t value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder addNodes(
          int index, com.mackenziehigh.sexpr.Message.node_t value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder addNodes(
          com.mackenziehigh.sexpr.Message.node_t.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder addNodes(
          int index, com.mackenziehigh.sexpr.Message.node_t.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends com.mackenziehigh.sexpr.Message.node_t> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.node_t.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.node_tOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public java.util.List<? extends com.mackenziehigh.sexpr.Message.node_tOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.node_t.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.mackenziehigh.sexpr.Message.node_t.getDefaultInstance());
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.node_t.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.mackenziehigh.sexpr.Message.node_t.getDefaultInstance());
      }
      /**
       * <code>repeated .sexpr.node_t nodes = 1;</code>
       */
      public java.util.List<com.mackenziehigh.sexpr.Message.node_t.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mackenziehigh.sexpr.Message.node_t, com.mackenziehigh.sexpr.Message.node_t.Builder, com.mackenziehigh.sexpr.Message.node_tOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mackenziehigh.sexpr.Message.node_t, com.mackenziehigh.sexpr.Message.node_t.Builder, com.mackenziehigh.sexpr.Message.node_tOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sexpr.message_t)
    }

    // @@protoc_insertion_point(class_scope:sexpr.message_t)
    private static final com.mackenziehigh.sexpr.Message.message_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mackenziehigh.sexpr.Message.message_t();
    }

    public static com.mackenziehigh.sexpr.Message.message_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<message_t>
        PARSER = new com.google.protobuf.AbstractParser<message_t>() {
      public message_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new message_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<message_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<message_t> getParserForType() {
      return PARSER;
    }

    public com.mackenziehigh.sexpr.Message.message_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface node_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sexpr.node_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.sexpr.location_t location = 1;</code>
     */
    boolean hasLocation();
    /**
     * <code>.sexpr.location_t location = 1;</code>
     */
    com.mackenziehigh.sexpr.Message.location_t getLocation();
    /**
     * <code>.sexpr.location_t location = 1;</code>
     */
    com.mackenziehigh.sexpr.Message.location_tOrBuilder getLocationOrBuilder();

    /**
     * <code>string valueAsString = 2;</code>
     */
    java.lang.String getValueAsString();
    /**
     * <code>string valueAsString = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueAsStringBytes();

    /**
     * <code>int64 valueAsLong = 3;</code>
     */
    long getValueAsLong();

    /**
     * <code>float valueAsFloat = 4;</code>
     */
    float getValueAsFloat();

    /**
     * <code>double valueAsDouble = 5;</code>
     */
    double getValueAsDouble();
  }
  /**
   * Protobuf type {@code sexpr.node_t}
   */
  public  static final class node_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sexpr.node_t)
      node_tOrBuilder {
    // Use node_t.newBuilder() to construct.
    private node_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private node_t() {
      valueAsString_ = "";
      valueAsLong_ = 0L;
      valueAsFloat_ = 0F;
      valueAsDouble_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private node_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.mackenziehigh.sexpr.Message.location_t.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(com.mackenziehigh.sexpr.Message.location_t.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              valueAsString_ = s;
              break;
            }
            case 24: {

              valueAsLong_ = input.readInt64();
              break;
            }
            case 37: {

              valueAsFloat_ = input.readFloat();
              break;
            }
            case 41: {

              valueAsDouble_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mackenziehigh.sexpr.Message.internal_static_sexpr_node_t_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mackenziehigh.sexpr.Message.internal_static_sexpr_node_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mackenziehigh.sexpr.Message.node_t.class, com.mackenziehigh.sexpr.Message.node_t.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    private com.mackenziehigh.sexpr.Message.location_t location_;
    /**
     * <code>.sexpr.location_t location = 1;</code>
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.sexpr.location_t location = 1;</code>
     */
    public com.mackenziehigh.sexpr.Message.location_t getLocation() {
      return location_ == null ? com.mackenziehigh.sexpr.Message.location_t.getDefaultInstance() : location_;
    }
    /**
     * <code>.sexpr.location_t location = 1;</code>
     */
    public com.mackenziehigh.sexpr.Message.location_tOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    public static final int VALUEASSTRING_FIELD_NUMBER = 2;
    private volatile java.lang.Object valueAsString_;
    /**
     * <code>string valueAsString = 2;</code>
     */
    public java.lang.String getValueAsString() {
      java.lang.Object ref = valueAsString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valueAsString_ = s;
        return s;
      }
    }
    /**
     * <code>string valueAsString = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueAsStringBytes() {
      java.lang.Object ref = valueAsString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valueAsString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUEASLONG_FIELD_NUMBER = 3;
    private long valueAsLong_;
    /**
     * <code>int64 valueAsLong = 3;</code>
     */
    public long getValueAsLong() {
      return valueAsLong_;
    }

    public static final int VALUEASFLOAT_FIELD_NUMBER = 4;
    private float valueAsFloat_;
    /**
     * <code>float valueAsFloat = 4;</code>
     */
    public float getValueAsFloat() {
      return valueAsFloat_;
    }

    public static final int VALUEASDOUBLE_FIELD_NUMBER = 5;
    private double valueAsDouble_;
    /**
     * <code>double valueAsDouble = 5;</code>
     */
    public double getValueAsDouble() {
      return valueAsDouble_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (location_ != null) {
        output.writeMessage(1, getLocation());
      }
      if (!getValueAsStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, valueAsString_);
      }
      if (valueAsLong_ != 0L) {
        output.writeInt64(3, valueAsLong_);
      }
      if (valueAsFloat_ != 0F) {
        output.writeFloat(4, valueAsFloat_);
      }
      if (valueAsDouble_ != 0D) {
        output.writeDouble(5, valueAsDouble_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLocation());
      }
      if (!getValueAsStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, valueAsString_);
      }
      if (valueAsLong_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, valueAsLong_);
      }
      if (valueAsFloat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, valueAsFloat_);
      }
      if (valueAsDouble_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, valueAsDouble_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mackenziehigh.sexpr.Message.node_t)) {
        return super.equals(obj);
      }
      com.mackenziehigh.sexpr.Message.node_t other = (com.mackenziehigh.sexpr.Message.node_t) obj;

      boolean result = true;
      result = result && (hasLocation() == other.hasLocation());
      if (hasLocation()) {
        result = result && getLocation()
            .equals(other.getLocation());
      }
      result = result && getValueAsString()
          .equals(other.getValueAsString());
      result = result && (getValueAsLong()
          == other.getValueAsLong());
      result = result && (
          java.lang.Float.floatToIntBits(getValueAsFloat())
          == java.lang.Float.floatToIntBits(
              other.getValueAsFloat()));
      result = result && (
          java.lang.Double.doubleToLongBits(getValueAsDouble())
          == java.lang.Double.doubleToLongBits(
              other.getValueAsDouble()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + VALUEASSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getValueAsString().hashCode();
      hash = (37 * hash) + VALUEASLONG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValueAsLong());
      hash = (37 * hash) + VALUEASFLOAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValueAsFloat());
      hash = (37 * hash) + VALUEASDOUBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValueAsDouble()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.node_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mackenziehigh.sexpr.Message.node_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sexpr.node_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sexpr.node_t)
        com.mackenziehigh.sexpr.Message.node_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_node_t_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_node_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mackenziehigh.sexpr.Message.node_t.class, com.mackenziehigh.sexpr.Message.node_t.Builder.class);
      }

      // Construct using com.mackenziehigh.sexpr.Message.node_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        valueAsString_ = "";

        valueAsLong_ = 0L;

        valueAsFloat_ = 0F;

        valueAsDouble_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_node_t_descriptor;
      }

      public com.mackenziehigh.sexpr.Message.node_t getDefaultInstanceForType() {
        return com.mackenziehigh.sexpr.Message.node_t.getDefaultInstance();
      }

      public com.mackenziehigh.sexpr.Message.node_t build() {
        com.mackenziehigh.sexpr.Message.node_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mackenziehigh.sexpr.Message.node_t buildPartial() {
        com.mackenziehigh.sexpr.Message.node_t result = new com.mackenziehigh.sexpr.Message.node_t(this);
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.valueAsString_ = valueAsString_;
        result.valueAsLong_ = valueAsLong_;
        result.valueAsFloat_ = valueAsFloat_;
        result.valueAsDouble_ = valueAsDouble_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mackenziehigh.sexpr.Message.node_t) {
          return mergeFrom((com.mackenziehigh.sexpr.Message.node_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mackenziehigh.sexpr.Message.node_t other) {
        if (other == com.mackenziehigh.sexpr.Message.node_t.getDefaultInstance()) return this;
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (!other.getValueAsString().isEmpty()) {
          valueAsString_ = other.valueAsString_;
          onChanged();
        }
        if (other.getValueAsLong() != 0L) {
          setValueAsLong(other.getValueAsLong());
        }
        if (other.getValueAsFloat() != 0F) {
          setValueAsFloat(other.getValueAsFloat());
        }
        if (other.getValueAsDouble() != 0D) {
          setValueAsDouble(other.getValueAsDouble());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mackenziehigh.sexpr.Message.node_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mackenziehigh.sexpr.Message.node_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.mackenziehigh.sexpr.Message.location_t location_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.mackenziehigh.sexpr.Message.location_t, com.mackenziehigh.sexpr.Message.location_t.Builder, com.mackenziehigh.sexpr.Message.location_tOrBuilder> locationBuilder_;
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.location_t getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? com.mackenziehigh.sexpr.Message.location_t.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public Builder setLocation(com.mackenziehigh.sexpr.Message.location_t value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public Builder setLocation(
          com.mackenziehigh.sexpr.Message.location_t.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public Builder mergeLocation(com.mackenziehigh.sexpr.Message.location_t value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              com.mackenziehigh.sexpr.Message.location_t.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.location_t.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      public com.mackenziehigh.sexpr.Message.location_tOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              com.mackenziehigh.sexpr.Message.location_t.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.sexpr.location_t location = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.mackenziehigh.sexpr.Message.location_t, com.mackenziehigh.sexpr.Message.location_t.Builder, com.mackenziehigh.sexpr.Message.location_tOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.mackenziehigh.sexpr.Message.location_t, com.mackenziehigh.sexpr.Message.location_t.Builder, com.mackenziehigh.sexpr.Message.location_tOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private java.lang.Object valueAsString_ = "";
      /**
       * <code>string valueAsString = 2;</code>
       */
      public java.lang.String getValueAsString() {
        java.lang.Object ref = valueAsString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          valueAsString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string valueAsString = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueAsStringBytes() {
        java.lang.Object ref = valueAsString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          valueAsString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string valueAsString = 2;</code>
       */
      public Builder setValueAsString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueAsString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string valueAsString = 2;</code>
       */
      public Builder clearValueAsString() {
        
        valueAsString_ = getDefaultInstance().getValueAsString();
        onChanged();
        return this;
      }
      /**
       * <code>string valueAsString = 2;</code>
       */
      public Builder setValueAsStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueAsString_ = value;
        onChanged();
        return this;
      }

      private long valueAsLong_ ;
      /**
       * <code>int64 valueAsLong = 3;</code>
       */
      public long getValueAsLong() {
        return valueAsLong_;
      }
      /**
       * <code>int64 valueAsLong = 3;</code>
       */
      public Builder setValueAsLong(long value) {
        
        valueAsLong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 valueAsLong = 3;</code>
       */
      public Builder clearValueAsLong() {
        
        valueAsLong_ = 0L;
        onChanged();
        return this;
      }

      private float valueAsFloat_ ;
      /**
       * <code>float valueAsFloat = 4;</code>
       */
      public float getValueAsFloat() {
        return valueAsFloat_;
      }
      /**
       * <code>float valueAsFloat = 4;</code>
       */
      public Builder setValueAsFloat(float value) {
        
        valueAsFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float valueAsFloat = 4;</code>
       */
      public Builder clearValueAsFloat() {
        
        valueAsFloat_ = 0F;
        onChanged();
        return this;
      }

      private double valueAsDouble_ ;
      /**
       * <code>double valueAsDouble = 5;</code>
       */
      public double getValueAsDouble() {
        return valueAsDouble_;
      }
      /**
       * <code>double valueAsDouble = 5;</code>
       */
      public Builder setValueAsDouble(double value) {
        
        valueAsDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double valueAsDouble = 5;</code>
       */
      public Builder clearValueAsDouble() {
        
        valueAsDouble_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sexpr.node_t)
    }

    // @@protoc_insertion_point(class_scope:sexpr.node_t)
    private static final com.mackenziehigh.sexpr.Message.node_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mackenziehigh.sexpr.Message.node_t();
    }

    public static com.mackenziehigh.sexpr.Message.node_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<node_t>
        PARSER = new com.google.protobuf.AbstractParser<node_t>() {
      public node_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new node_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<node_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<node_t> getParserForType() {
      return PARSER;
    }

    public com.mackenziehigh.sexpr.Message.node_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface location_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sexpr.location_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string source = 1;</code>
     */
    java.lang.String getSource();
    /**
     * <code>string source = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>int32 line = 2;</code>
     */
    int getLine();

    /**
     * <code>int32 column = 3;</code>
     */
    int getColumn();
  }
  /**
   * Protobuf type {@code sexpr.location_t}
   */
  public  static final class location_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sexpr.location_t)
      location_tOrBuilder {
    // Use location_t.newBuilder() to construct.
    private location_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private location_t() {
      source_ = "";
      line_ = 0;
      column_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private location_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 16: {

              line_ = input.readInt32();
              break;
            }
            case 24: {

              column_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mackenziehigh.sexpr.Message.internal_static_sexpr_location_t_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mackenziehigh.sexpr.Message.internal_static_sexpr_location_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mackenziehigh.sexpr.Message.location_t.class, com.mackenziehigh.sexpr.Message.location_t.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object source_;
    /**
     * <code>string source = 1;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <code>string source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINE_FIELD_NUMBER = 2;
    private int line_;
    /**
     * <code>int32 line = 2;</code>
     */
    public int getLine() {
      return line_;
    }

    public static final int COLUMN_FIELD_NUMBER = 3;
    private int column_;
    /**
     * <code>int32 column = 3;</code>
     */
    public int getColumn() {
      return column_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, source_);
      }
      if (line_ != 0) {
        output.writeInt32(2, line_);
      }
      if (column_ != 0) {
        output.writeInt32(3, column_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, source_);
      }
      if (line_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, line_);
      }
      if (column_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, column_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mackenziehigh.sexpr.Message.location_t)) {
        return super.equals(obj);
      }
      com.mackenziehigh.sexpr.Message.location_t other = (com.mackenziehigh.sexpr.Message.location_t) obj;

      boolean result = true;
      result = result && getSource()
          .equals(other.getSource());
      result = result && (getLine()
          == other.getLine());
      result = result && (getColumn()
          == other.getColumn());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine();
      hash = (37 * hash) + COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getColumn();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mackenziehigh.sexpr.Message.location_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mackenziehigh.sexpr.Message.location_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sexpr.location_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sexpr.location_t)
        com.mackenziehigh.sexpr.Message.location_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_location_t_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_location_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mackenziehigh.sexpr.Message.location_t.class, com.mackenziehigh.sexpr.Message.location_t.Builder.class);
      }

      // Construct using com.mackenziehigh.sexpr.Message.location_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = "";

        line_ = 0;

        column_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mackenziehigh.sexpr.Message.internal_static_sexpr_location_t_descriptor;
      }

      public com.mackenziehigh.sexpr.Message.location_t getDefaultInstanceForType() {
        return com.mackenziehigh.sexpr.Message.location_t.getDefaultInstance();
      }

      public com.mackenziehigh.sexpr.Message.location_t build() {
        com.mackenziehigh.sexpr.Message.location_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mackenziehigh.sexpr.Message.location_t buildPartial() {
        com.mackenziehigh.sexpr.Message.location_t result = new com.mackenziehigh.sexpr.Message.location_t(this);
        result.source_ = source_;
        result.line_ = line_;
        result.column_ = column_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mackenziehigh.sexpr.Message.location_t) {
          return mergeFrom((com.mackenziehigh.sexpr.Message.location_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mackenziehigh.sexpr.Message.location_t other) {
        if (other == com.mackenziehigh.sexpr.Message.location_t.getDefaultInstance()) return this;
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (other.getLine() != 0) {
          setLine(other.getLine());
        }
        if (other.getColumn() != 0) {
          setColumn(other.getColumn());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mackenziehigh.sexpr.Message.location_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mackenziehigh.sexpr.Message.location_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>string source = 1;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string source = 1;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string source = 1;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>string source = 1;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private int line_ ;
      /**
       * <code>int32 line = 2;</code>
       */
      public int getLine() {
        return line_;
      }
      /**
       * <code>int32 line = 2;</code>
       */
      public Builder setLine(int value) {
        
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 line = 2;</code>
       */
      public Builder clearLine() {
        
        line_ = 0;
        onChanged();
        return this;
      }

      private int column_ ;
      /**
       * <code>int32 column = 3;</code>
       */
      public int getColumn() {
        return column_;
      }
      /**
       * <code>int32 column = 3;</code>
       */
      public Builder setColumn(int value) {
        
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 column = 3;</code>
       */
      public Builder clearColumn() {
        
        column_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sexpr.location_t)
    }

    // @@protoc_insertion_point(class_scope:sexpr.location_t)
    private static final com.mackenziehigh.sexpr.Message.location_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mackenziehigh.sexpr.Message.location_t();
    }

    public static com.mackenziehigh.sexpr.Message.location_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<location_t>
        PARSER = new com.google.protobuf.AbstractParser<location_t>() {
      public location_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new location_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<location_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<location_t> getParserForType() {
      return PARSER;
    }

    public com.mackenziehigh.sexpr.Message.location_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sexpr_message_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sexpr_message_t_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sexpr_node_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sexpr_node_t_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sexpr_location_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sexpr_location_t_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\005sexpr\")\n\tmessage_t\022\034\n\005n" +
      "odes\030\001 \003(\0132\r.sexpr.node_t\"\206\001\n\006node_t\022#\n\010" +
      "location\030\001 \001(\0132\021.sexpr.location_t\022\025\n\rval" +
      "ueAsString\030\002 \001(\t\022\023\n\013valueAsLong\030\003 \001(\003\022\024\n" +
      "\014valueAsFloat\030\004 \001(\002\022\025\n\rvalueAsDouble\030\005 \001" +
      "(\001\":\n\nlocation_t\022\016\n\006source\030\001 \001(\t\022\014\n\004line" +
      "\030\002 \001(\005\022\016\n\006column\030\003 \001(\005B\031\n\027com.mackenzieh" +
      "igh.sexprb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sexpr_message_t_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sexpr_message_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sexpr_message_t_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_sexpr_node_t_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sexpr_node_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sexpr_node_t_descriptor,
        new java.lang.String[] { "Location", "ValueAsString", "ValueAsLong", "ValueAsFloat", "ValueAsDouble", });
    internal_static_sexpr_location_t_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sexpr_location_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sexpr_location_t_descriptor,
        new java.lang.String[] { "Source", "Line", "Column", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
